<a href="https://colab.research.google.com/github/Haya146/Python-tutorial-notebooks/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np

In [ ]:
# Three rows
# First row starts with 7 and contains 5 elements
# Second row sarts with 9 and contains 5 elements
# third row starts with 11 and conains 5 elements
a = np.array([range(i,i+5) for i in [10,20,30]])
a

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [ ]:
list = [1,2,'saed',3.4]
list

[1, 2, 'saed', 3.4]

In [ ]:
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
# Only one Data type          string -> float ->int
a = np.array([1,2,3,'saed',5])
a

array(['1', '2', '3', 'saed', '5'], dtype='<U21')

In [ ]:
a = np.array([1,2,3,0.5,6])
a

array([1. , 2. , 3. , 0.5, 6. ])

In [ ]:
a = np.array([1,2,3,4,5])
print(a.ndim) # dimensional

1


In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [ ]:
a = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(a)
print(a.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
3


In [ ]:
a = np.array([1,2,3,4,5],dtype = float)
a

array([1., 2., 3., 4., 5.])

In [ ]:
a= np.zeros(10,dtype = int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
a = np.ones(10, dtype= int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
a = np.ones((3,5), dtype= int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.ones((3,5,3), dtype= int)
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [ ]:
 a=np.eye(5, dtype= int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
a = np.full((3,5),4)
a

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(0,10.2)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
a = np.random.random((3,3))   #0-1
a

array([[0.48872276, 0.21387882, 0.17549248],
       [0.40858298, 0.86144866, 0.63013851],
       [0.83361677, 0.00307266, 0.26383811]])

In [ ]:
a= np.random.normal(0,1,(3,3))
a

array([[ 0.10043584,  1.13163595, -1.42282304],
       [ 0.99874717, -0.30112164,  0.15259832],
       [ 0.52825365,  0.83469824,  0.59420931]])

In [ ]:
a = np.random.randint(0,5,(3,3))
a

array([[3, 3, 0],
       [2, 1, 0],
       [0, 3, 0]])

In [ ]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 5)

In [ ]:
x.size

10

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.itemsize

8

In [ ]:
x.nbytes

80

In [ ]:
x.shape

(2, 5)

In [ ]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
new = x.reshape(5,2)
new

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
x[0][2]

3

In [ ]:
x[1],[3]

(array([ 6,  7,  8,  9, 10]), [3])

In [ ]:
x[1][-1]

10

In [ ]:
x[1,2] = 900
x

array([[  1,   2,   3,   4,   5],
       [  6,   7, 900,   9,  10]])

In [ ]:
x = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
x[0,2,2]

11

In [ ]:
x[1,0,2]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
x+5

array([[[ 6,  7,  8,  9],
        [10, 11, 12, 13],
        [14, 15, 16, 17]]])

In [ ]:
x*3

array([[[ 3,  6,  9, 12],
        [15, 18, 21, 24],
        [27, 30, 33, 36]]])

In [ ]:
n = np.array([1,2,3,4,5,6,7,8,9,10])
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
n[1:5]

array([2, 3, 4, 5])

In [ ]:
n[ :4]

array([1, 2, 3, 4])

In [ ]:
n[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
n[ ::2]

array([1, 3, 5, 7, 9])

In [ ]:
n[2::3]

array([3, 6, 9])

In [ ]:
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
n[5::-2]

array([6, 4, 2])

In [ ]:
q = np.array([[1,2,3,4,5],[6,7,8,9,10]])
q

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
q[1,1:3]

array([7, 8])

In [ ]:
q[1, :]

array([ 6,  7,  8,  9, 10])

In [ ]:
q[1,::2]

array([ 6,  8, 10])

In [ ]:
q[1,-1]

10

In [ ]:
q

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
q[1,:-1:2]

array([6, 8])

In [ ]:
q

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
q[0:2, 0:2]

array([[1, 2],
       [6, 7]])

In [ ]:
q[0:2,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [ ]:
q[0:2,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6]])

In [ ]:
q[0,::-1]

array([5, 4, 3, 2, 1])

In [ ]:
# dim row col

In [ ]:
a = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
a

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [ ]:
# dim row col
a[0:3, 0:3, 1:3]

array([[[ 2,  3],
        [ 7,  8],
        [12, 13]]])

In [ ]:
a[0:3, 2, 1:3]

array([[12, 13]])

In [ ]:
a[0:3, -2,-2]

array([9])

In [ ]:
# exercise1
'''
قرر برعي الحصول على قوام رشيق وفقدانلا بعض الوزن
وقام بتسجيل وزنه كل يوم لمدة خمسة اسابيع بدءا من يوم السبت
فاذا علمت ان وزنه كان 83.25 كجم
ومعدل خسارة الوزن يوميا 200 جم
والمتاح له من الوقت نفسه يومي الخميس والجمعه
احسب متوسط الوزن نهاية الاسبوع


'''

In [ ]:
# initial parameters

initial_weight = 83.25  #kg
daily_loss = 0.2  #kg per day
days_in_week = 7
weeks = 5

# weekly weight loss
weekly_loss = daily_loss * days_in_week

# calculate weight at the end of each week
weekly_weights = initial_weight -(np.arange(1, weeks+1)* weekly_loss)

# calculate average weight at the end of each week
average_weekly_weight = np.mean(weekly_weights)
average_weekly_weight

79.05

## copy vs view

In [ ]:
a = np.array ([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
x= a.copy()
x

array([1, 2, 3, 4, 5])

In [ ]:
a[0] = 400
print(a)
print(x)

[400 900   3   4   5]
[1 2 3 4 5]


In [ ]:
z= a.view()
z

array([400, 900,   3,   4,   5])

In [ ]:
a[1] = 900
print(a)
print(z)

[400 900   3   4   5]
[400 900   3   4   5]


In [ ]:
z[3] = 100
print(a)
print(z)

[400 900   3 100   5]
[400 900   3 100   5]


## Resape and Resize

In [ ]:
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
 

In [ ]:
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a.shape

(20,)

In [ ]:
a.size

20

In [ ]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [ ]:
a.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])